### PR TITLE
Use project's github package.json

### PR DESCRIPTION
**Pull request by cbornet**
See https://github.com/jhipster/generator-jhipster/issues/2633

### CODE REVIEW

**Comment by deepu105** [comment]
@cbornet, i guess the links should point to master branch rite? Also the keywords we had in the modules were different from what is in package json. Thise were for serach within marketplace.

**Comment by cbornet** [comment]
Indeed, @jdubois do we need separate keywords between npm and jhipster module ?
As for pointing to the master branch, you can do that but if you change things like the jhipster version in master that you don't push to an npm release, there can be incorrect information output on the website. Anyway, it's just a path so anyone can make it point according to its own preferences.

**Comment by deepu105** [comment]
@cbornet I personally do not like this, the old module.json way or your proxy way is better than this

This way would require module maintainers to update the jhipster site for each release with PR, its more maintenance, so lets keep the old module json way or the proxy way

**Comment by cbornet** [comment]
With the module.json way you also have to PR each time you want a change. And as for the proxy @jdubois has concerns regarding proxy downtime.

**Comment by cbornet** [comment]
Maybe we could have a dedicated json file in the gh master branch? This way you can update the info as much as you want.

**Comment by deepu105** [comment]
With module json its one time update mostly unless someone wants to change
name, author etc. But having a specific package json path means you have to
update it for each time you publish a package, and having master package
might be misleading as well.

I like the proxy way, Julien's concern is on availability of the service,
coz if it goes down things will fail.

May be we can do this, since module authors need to PR the module json
once, let them fill in all details as per today. In the module page you can
use the proxy call to get latest npm info and if that call fails then we
can fall back to module.json info this way we need not be worried about
availability as well what say?

**Comment by cbornet** [comment]
You don't need to update the package.json path at each release ! It's the same as module.json : you PR only when you want to change author, jhipster dependency, ...

**Comment by cbornet** [comment]
As for the fallback I think this is a very good idea.

**Comment by cbornet** [comment]
We could have npm registry with fallback to gh

**Comment by deepu105** [comment]
In your PR the path was like this 
`"npmPackagePath": "https://raw.githubusercontent.com/jdubois/generator-jhipster-fortune/v0.0.2/package.json",`
and this
`"npmPackagePath": "https://raw.githubusercontent.com/moifort/generator-jhipster-angular-ui/master/package.json",`

 so If there is a new version someone has to update this path, if its the master that means people will see un released version numbers

I would prefer NPM registry via proxy and the module.json details as fallback, coz the above isnt very maintanance friendly and people tend to get confused and easy to do mistake there

**Comment by deepu105** [comment]
btw I had moved all js files to js folder since we are not having a perfect angular only app here, its a mix and match of angular, jquery and jekyll so better to have in js folder so it can be easily reused

**Comment by deepu105** [comment]
@cbornet @jdubois take a look at this https://github.com/slushjs/generators/blob/master/src/app/generators/generators-controller.js

Shouldn't this be a better way to get all Jhipster modules,so that module writers need not PR to the modules.json at all? we could maintain a map to mark verified generators

we can use the jhipster-module keyword to search like this

http://npmsearch.com/query?fields=name,keywords,description,author,homepage,version&q=keywords:jhipster-module&size=20&start=0

which gives below
```
{  
   "results":[  
      {  
         "author":[  
            "deepu8224"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "homepage":[  
            "https://github.com/deepu105/generator-jhipster-entity-audit"
         ],
         "description":[  
            "JHipster module to enable entity audit and audit log page"
         ],
         "version":[  
            "1.0.4"
         ],
         "name":[  
            "generator-jhipster-entity-audit"
         ]
      },
      {  
         "author":[  
            "cbornet"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "homepage":[  
            "https://github.com/cbornet/generator-jhipster-debian-packager"
         ],
         "description":[  
            "Packages a JHipster application into a debian/ubuntu .deb package"
         ],
         "version":[  
            "0.3.0"
         ],
         "name":[  
            "generator-jhipster-debian-packager"
         ]
      },
      {  
         "author":[  
            "moifort"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "homepage":[  
            "https://github.com/moifort/generator-jhipster-google-analytics"
         ],
         "description":[  
            "Install Google analytics on your JHipster app"
         ],
         "version":[  
            "0.0.1"
         ],
         "name":[  
            "generator-jhipster-google-analytics"
         ]
      },
      {  
         "author":[  
            "deepu8224"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "homepage":[  
            "https://github.com/deepu105/generator-jhipster-entity-audit"
         ],
         "description":[  
            "Jhipster module to scaffold soap and rest webservices"
         ],
         "version":[  
            "0.1.0"
         ],
         "name":[  
            "generator-jhipster-webservice"
         ]
      },
      {  
         "author":[  
            "pascalgrimaud"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "homepage":[  
            "https://github.com/jhipster/generator-jhipster-module"
         ],
         "description":[  
            "JHipster module, used to create a JHipster module"
         ],
         "version":[  
            "0.0.8"
         ],
         "name":[  
            "generator-jhipster-module"
         ]
      },
      {  
         "author":[  
            "moifort"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "homepage":[  
            "https://github.com/moifort/generator-jhipster-angular-ui"
         ],
         "description":[  
            "Install AngularUI module on your JHipster app"
         ],
         "version":[  
            "0.0.2"
         ],
         "name":[  
            "generator-jhipster-angular-ui"
         ]
      },
      {  
         "author":[  
            "geraldhumphries"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "homepage":[  
            "https://github.com/geraldhumphries/generator-jhipster-elasticsearch-reindexer"
         ],
         "description":[  
            "Generate a service for reindexing all database rows for each of your entities"
         ],
         "version":[  
            "0.0.5"
         ],
         "name":[  
            "generator-jhipster-elasticsearch-reindexer"
         ]
      },
      {  
         "author":[  
            "deepu8224"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "homepage":[  
            "https://github.com/deepu105/generator-jhipster-bootswatch"
         ],
         "description":[  
            "A jhipster mdoule to enable bootswatch theme switcher to generated application"
         ],
         "version":[  
            "0.2.1"
         ],
         "name":[  
            "generator-jhipster-bootswatch"
         ]
      },
      {  
         "author":[  
            "moifort"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "homepage":[  
            "https://github.com/moifort/generator-jhipster-google-maps"
         ],
         "description":[  
            "Install Google maps sample on your JHipster app"
         ],
         "version":[  
            "0.0.1"
         ],
         "name":[  
            "generator-jhipster-google-maps"
         ]
      },
      {  
         "author":[  
            "atomfrede"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "homepage":[  
            "https://github.com/atomfrede/generator-jhipster-leaflet"
         ],
         "description":[  
            "JHipster module to install a sample of ui-leaflet maps on your JHipster application."
         ],
         "version":[  
            "0.0.1"
         ],
         "name":[  
            "generator-jhipster-leaflet"
         ]
      },
      {  
         "author":[  
            "deepu8224"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module",
            "Jhipster-react"
         ],
         "homepage":[  
            "https://github.com/deepu105/generator-jhipster-react"
         ],
         "description":[  
            "A Jhipster based generator to create react + spring boot application"
         ],
         "version":[  
            "0.0.0"
         ],
         "name":[  
            "generator-jhipster-react"
         ]
      },
      {  
         "author":[  
            "moifort"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "homepage":[  
            "https://github.com/moifort/generator-jhipster-bootstrap-material-design"
         ],
         "description":[  
            "Add Material design to your JHipster application"
         ],
         "version":[  
            "0.0.1"
         ],
         "name":[  
            "generator-jhipster-bootstrap-material-design"
         ]
      },
      {  
         "author":[  
            "cbornet"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "homepage":[  
            "https://github.com/cbornet/generator-jhipster-basic-auth"
         ],
         "description":[  
            "Adds stateless basic authentication support"
         ],
         "version":[  
            "0.2.0"
         ],
         "name":[  
            "generator-jhipster-basic-auth"
         ]
      },
      {  
         "author":[  
            "pascalgrimaud"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module",
            "docker",
            "docker-compose"
         ],
         "homepage":[  
            "https://github.com/pascalgrimaud/generator-jhipster-docker"
         ],
         "description":[  
            "JHipster module, Docker support in your JHipster application"
         ],
         "version":[  
            "0.0.13"
         ],
         "name":[  
            "generator-jhipster-docker"
         ]
      },
      {  
         "author":[  
            "atomfrede"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "homepage":[  
            "https://github.com/atomfrede/generator-jhipster-swagger2markup"
         ],
         "description":[  
            "JHipster module to create nice looking static api docs with swagger2markup"
         ],
         "version":[  
            "0.0.10"
         ],
         "name":[  
            "generator-jhipster-swagger2markup"
         ]
      },
      {  
         "author":[  
            "pascalgrimaud"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module",
            "continuous",
            "integration",
            "test"
         ],
         "homepage":[  
            "https://github.com/pascalgrimaud/generator-jhipster-ci"
         ],
         "description":[  
            "JHipster module, Continuous Integration support in your JHipster application"
         ],
         "version":[  
            "0.0.4"
         ],
         "name":[  
            "generator-jhipster-ci"
         ]
      },
      {  
         "author":[  
            "jdubois"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "homepage":[  
            "https://github.com/jdubois/generator-jhipster-fortune"
         ],
         "description":[  
            "Sample JHipster module, generates a \"fortune cookie\" page in your JHipster application"
         ],
         "version":[  
            "0.0.2"
         ],
         "name":[  
            "generator-jhipster-fortune"
         ]
      }
   ],
   "total":17,
   "size":"20",
   "from":"0"
}
```

**Comment by deepu105** [comment]
i like their UI using this as well http://slushjs.github.io/generators/#/
we should also do list instead of table, table is so oldschool

**Comment by cbornet** [comment]
Great idea ! We should totally do that : it's one request instead of one per module !
I guess CORS is ok with npmsearch since it works with slushjs.

**Comment by cbornet** [comment]
I see some issues with npmsearch : 
* the author is the gh user, not the npm package author structure with author name and author url
* it doesn't output the versions of dependencies (eg. generator-jhipster)

**Comment by deepu105** [comment]
@cbornet for author it is giving the npm author name alone, there is no author url, but gives repo url and i guess we can use that to point to the authors github page so that might not be a big issue.

But i dont have a solution for dependency version :( may be we could use the proxy to get it from npm for that alone, so even if it fails module listing will still be present.

Coz with most plugin based systems there, they search using keywords to show whats available rather than asking plugin writers to PR for changes to directory, in the long run, when we have a lot of modules, may be we could run our own aggregator to find and index available modules

```
{  
         "author":[  
            "deepu8224"
         ],
         "keywords":[  
            "yeoman-generator",
            "jhipster-module"
         ],
         "created":[  
            "2015-12-29T05:12:08.500Z"
         ],
         "repository":[  
            "git+https://github.com/deepu105/generator-jhipster-entity-audit.git"
         ],
         "description":[  
            "JHipster module to enable entity audit and audit log page"
         ],
         "name":[  
            "generator-jhipster-entity-audit"
         ],
         "homepage":[  
            "https://github.com/deepu105/generator-jhipster-entity-audit"
         ],
         "version":[  
            "1.0.4"
         ]
      },
```

**Pull request closed without merging**
